webauthin/urls.py
from django.urls import path

from . import views


app_name = "webauthin"
urlpatterns = [
    path(r"login/begin/", views.login_begin, name="login-begin"),
    path(r"login/verify/", views.login_verify, name="login-verify"),
    path(r"register/begin/", views.register_begin, name="register-begin"),
    path(r"register/verify/", views.register_verify, name="register-verify"),
    path(r"key/rename/", views.rename_key, name="rename-key"),
    path(r"key/delete/", views.delete_key, name="delete-key"),
    path(r"login/", views.login_view, name="login"),
]

webauthin/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.timezone import now


class AuthData(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(
        max_length=200, blank=True, help_text="The user-friendly name for this key."
    )
    credential_id = models.CharField(max_length=300, unique=True)
    public_key = models.CharField(max_length=500)
    sign_count = models.IntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    last_used_on = models.DateTimeField(default=now)

    class Meta:
        verbose_name_plural = "auth data"

    def set_sign_count(self, sign_count: int) -> None:
        """Set the sign_count and update the last_used_on datetime."""
        self.sign_count = sign_count
        self.last_used_on = now()
        self.save()

    def __str__(self):
        return self.name or str(self.user)

webauthin/views.py
from base64 import b64decode, b64encode

from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from pydantic.error_wrappers import ValidationError

from webauthn import (
    generate_authentication_options,
    generate_registration_options,
    options_to_json,
    verify_registration_response,
)
from webauthn.helpers import generate_challenge
from webauthn.helpers.exceptions import InvalidRegistrationResponse
from webauthn.helpers.structs import (
    AttestationConveyancePreference,
    AuthenticationCredential,
    AuthenticatorSelectionCriteria,
    RegistrationCredential,
    ResidentKeyRequirement,
    UserVerificationRequirement,
)

from . import settings as wa_settings
from .models import AuthData


User = get_user_model()


def login_view(request):
    return render(request, "webauthin_login.html")


@csrf_exempt
@login_required
def register_begin(request):
    site = get_current_site(request)
    hostname = site.domain.split(":")[0]
    challenge = generate_challenge()
    request.session["challenge"] = b64encode(challenge).decode()
    registration_options = generate_registration_options(
        rp_id=hostname,
        rp_name=site.name,
        user_id=b64encode(str(request.user.id).encode()).decode(),
        user_name=request.user.get_username(),
        user_display_name=f"{site.name} user: {request.user.get_username()}",
        challenge=challenge,
        attestation=AttestationConveyancePreference.NONE,
        authenticator_selection=AuthenticatorSelectionCriteria(
            resident_key=ResidentKeyRequirement.REQUIRED,
            user_verification=UserVerificationRequirement.REQUIRED,
        ),
    )

    return HttpResponse(options_to_json(registration_options), content_type="application/json")


@csrf_exempt
@login_required
def register_verify(request):
    site = get_current_site(request)
    hostname = site.domain.split(":")[0]
    encoded_challenge = request.session.get("challenge")
    if not encoded_challenge:
        return JsonResponse("No challenge exists in your session.", status=422)

    challenge = b64decode(encoded_challenge)

    try:
        credential = RegistrationCredential.parse_raw(request.POST)
    except ValidationError:
        messages.error(request, "Invalid authentication data.")
        return redirect(wa_settings.LOGIN_ERROR_URL)

    try:
        registration_verification = verify_registration_response(
            credential=credential,
            expected_challenge=challenge,
            expected_rp_id=hostname,
            expected_origin=f"https://{site.domain}",
            require_user_verification=True,
        )
    except InvalidRegistrationResponse as e:
        messages.error(request, "Registration failed. Error: {}".format(e))
        return redirect(wa_settings.REGISTRATION_ERROR_URL)

    auth_data = AuthData.objects.filter(credential_id=registration_verification.credential_id.decode())
    if auth_data.exists():
        messages.error(
            request,
            "This key is already registered to an account. Try logging in with it.",
        )
        return redirect(wa_settings.REGISTRATION_ERROR_URL)

    AuthData.objects.create(
        user=request.user,
        credential_id=registration_verification.credential_id.decode(),
        public_key=registration_verification.credential_public_key.decode(),
    )
    messages.success(request, "Your key has been successfully registered.")
    return redirect(wa_settings.REGISTRATION_REDIRECT_URL)


@csrf_exempt
def login_begin(request):
    site = get_current_site(request)
    hostname = site.domain.split(":")[0]
    challenge = generate_challenge()
    request.session["challenge"] = b64encode(challenge).decode()
    authentication_options = generate_authentication_options(
        rp_id=hostname,
        challenge=challenge,
        user_verification=UserVerificationRequirement.REQUIRED,
    )

    return HttpResponse(options_to_json(authentication_options), content_type="application/json")


@csrf_exempt
def login_verify(request):
    encoded_challenge = request.session.get("challenge")
    if not encoded_challenge:
        messages.error(request, "No challenge exists for your session.")
        return redirect(wa_settings.LOGIN_ERROR_URL)

    try:
        credential = AuthenticationCredential.parse_raw(request.POST)
    except ValidationError:
        messages.error(request, "Invalid authentication data.")
        return redirect(wa_settings.LOGIN_ERROR_URL)

    user = authenticate(request, credential=credential)
    if user is None:
        messages.error(request, "Your credentials could not be validated.")
        return redirect(wa_settings.LOGIN_ERROR_URL)

    login(request, user)

    messages.success(request, "You have been successfully logged in.")
    return redirect(wa_settings.LOGIN_REDIRECT_URL)


@login_required
def rename_key(request):
    key = AuthData.objects.filter(pk=request.POST["key_id"]).first()
    if not key or key.user != request.user:
        messages.error(request, "That key does not exist.")
    else:
        key.name = request.POST["name"]
        key.save()
        messages.success(request, "The key has been renamed.")
    return redirect(wa_settings.REGISTRATION_REDIRECT_URL)


@login_required
def delete_key(request):
    key = AuthData.objects.filter(pk=request.POST["key_id"]).first()
    if not key or key.user != request.user:
        messages.error(request, "That key does not exist.")
    else:
        key.delete()
        messages.success(request, "The key has been deleted.")
    return redirect(wa_settings.REGISTRATION_REDIRECT_URL)

webauthin/templates/webauthin_login.html
{% block content %}
<script>
    var lookup = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

    ;(function (exports) {
        'use strict'

        var Arr = (typeof Uint8Array !== 'undefined')
        ? Uint8Array
        : Array

        var PLUS = '+'.charCodeAt(0)
        var SLASH = '/'.charCodeAt(0)
        var NUMBER = '0'.charCodeAt(0)
        var LOWER = 'a'.charCodeAt(0)
        var UPPER = 'A'.charCodeAt(0)
        var PLUS_URL_SAFE = '-'.charCodeAt(0)
        var SLASH_URL_SAFE = '_'.charCodeAt(0)

        function decode (elt) {
            var code = elt.charCodeAt(0)
            if (code === PLUS || code === PLUS_URL_SAFE) return 62 // '+'
            if (code === SLASH || code === SLASH_URL_SAFE) return 63 // '/'
            if (code < NUMBER) return -1 // no match
            if (code < NUMBER + 10) return code - NUMBER + 26 + 26
            if (code < UPPER + 26) return code - UPPER
            if (code < LOWER + 26) return code - LOWER + 26
        }

        function b64ToByteArray (b64) {
            var i, j, l, tmp, placeHolders, arr

            if (b64.length % 4 > 0) {
                throw new Error('Invalid string. Length must be a multiple of 4')
            }

            // the number of equal signs (place holders)
            // if there are two placeholders, than the two characters before it
            // represent one byte
            // if there is only one, then the three characters before it represent 2 bytes
            // this is just a cheap hack to not do indexOf twice
            var len = b64.length
            placeHolders = b64.charAt(len - 2) === '=' ? 2 : b64.charAt(len - 1) === '=' ? 1 : 0

            // base64 is 4/3 + up to two characters of the original data
            arr = new Arr(b64.length * 3 / 4 - placeHolders)

            // if there are placeholders, only get up to the last complete 4 chars
            l = placeHolders > 0 ? b64.length - 4 : b64.length

            var L = 0

            function push (v) {
                arr[L++] = v
            }

            for (i = 0, j = 0; i < l; i += 4, j += 3) {
                tmp = (decode(b64.charAt(i)) << 18) | (decode(b64.charAt(i + 1)) << 12) | (decode(b64.charAt(i + 2)) << 6) | decode(b64.charAt(i + 3))
                push((tmp & 0xFF0000) >> 16)
                push((tmp & 0xFF00) >> 8)
                push(tmp & 0xFF)
            }

            if (placeHolders === 2) {
                tmp = (decode(b64.charAt(i)) << 2) | (decode(b64.charAt(i + 1)) >> 4)
                push(tmp & 0xFF)
                } else if (placeHolders === 1) {
                tmp = (decode(b64.charAt(i)) << 10) | (decode(b64.charAt(i + 1)) << 4) | (decode(b64.charAt(i + 2)) >> 2)
                push((tmp >> 8) & 0xFF)
                push(tmp & 0xFF)
            }

            return arr
        }

        function uint8ToBase64 (uint8) {
            var i
            var extraBytes = uint8.length % 3 // if we have 1 byte left, pad 2 bytes
            var output = ''
            var temp, length

            function encode (num) {
                return lookup.charAt(num)
            }

            function tripletToBase64 (num) {
                return encode(num >> 18 & 0x3F) + encode(num >> 12 & 0x3F) + encode(num >> 6 & 0x3F) + encode(num & 0x3F)
            }

            // go through the array every three bytes, we'll deal with trailing stuff later
            for (i = 0, length = uint8.length - extraBytes; i < length; i += 3) {
                temp = (uint8[i] << 16) + (uint8[i + 1] << 8) + (uint8[i + 2])
                output += tripletToBase64(temp)
            }

            // pad the end with zeros, but make sure to not forget the extra bytes
            switch (extraBytes) {
                case 1:
                temp = uint8[uint8.length - 1]
                output += encode(temp >> 2)
                output += encode((temp << 4) & 0x3F)
                output += '=='
                break
                case 2:
                temp = (uint8[uint8.length - 2] << 8) + (uint8[uint8.length - 1])
                output += encode(temp >> 10)
                output += encode((temp >> 4) & 0x3F)
                output += encode((temp << 2) & 0x3F)
                output += '='
                break
                default:
                break
            }

            return output
        }

        exports.toByteArray = b64ToByteArray
        exports.fromByteArray = uint8ToBase64
    }(typeof exports === 'undefined' ? (this.base64js = {}) : exports))



    function b64enc(buf) {
        return base64js.fromByteArray(buf)
        .replace(/\+/g, "-")
        .replace(/\//g, "_")
        .replace(/=/g, "");
    }

    function b64RawEnc(buf) {
        return base64js.fromByteArray(buf)
        .replace(/\+/g, "-")
        .replace(/\//g, "_");
    }

    function hexEncode(buf) {
        return Array.from(buf)
        .map(function(x) {
            return ("0" + x.toString(16)).substr(-2);
        })
        .join("");
    }

    function urlsafe_b64decode(s) {
        return atob(s.replace(/\-/g, '+').replace(/_/g, '/'));
    }

    async function fetch_json(url, options) {
        const response = await fetch(url, options);
        const body = await response.json();
        if (body.fail)
        throw body.fail;
        return body;
    }

    /**
    * Get PublicKeyCredentialRequestOptions for this user from the server
    * formData of the registration form
    * @param {FormData} formData
    */
    const getCredentialRequestOptionsFromServer = async () => {
        return await fetch_json(
        "{% url "webauthin:login-begin" %}", {
            method: "POST",
        }
        );
    }

    const transformCredentialRequestOptions = (credentialRequestOptionsFromServer) => {
        let {challenge, allowCredentials} = credentialRequestOptionsFromServer;

        challenge = Uint8Array.from(
        urlsafe_b64decode(challenge), c => c.charCodeAt(0));

        allowCredentials = allowCredentials.map(credentialDescriptor => {
            let {id} = credentialDescriptor;
            id = Uint8Array.from(urlsafe_b64decode(id), c => c.charCodeAt(0));
            return Object.assign({}, credentialDescriptor, {id});
        });

        const transformedCredentialRequestOptions = Object.assign(
        {},
        credentialRequestOptionsFromServer,
        {challenge, allowCredentials});

        return transformedCredentialRequestOptions;
    };


    /**
    * Callback executed after submitting login form
    * @param {Event} e
    */
    const didClickLogin = async (e) => {
        e.preventDefault();
        if (navigator.credentials == undefined) {
            alert("Your browser doesn't support WebAuthn, please use a different browser.");
            return;
        }

        let credentialCreateOptionsFromServer;
        try {
            credentialRequestOptionsFromServer = await getCredentialRequestOptionsFromServer();
        } catch (err) {
            return console.error("Error when getting request options from server:", err);
        }

        const transformedCredentialRequestOptions = transformCredentialRequestOptions(credentialRequestOptionsFromServer);

        let assertion;
        try {
            assertion = await navigator.credentials.get({
                publicKey: transformedCredentialRequestOptions,
            });
        } catch (err) {
            alert("Error when creating credential: " + err);
            return console.error("Error when creating credential: ", err);
        }

        const transformedAssertionForServer = transformAssertionForServer(assertion);

        postAssertionToServer(transformedAssertionForServer);
    };

    /**
    * Encodes the binary data in the assertion into strings for posting to the server.
    * @param {PublicKeyCredential} newAssertion
    */
    const transformAssertionForServer = (newAssertion) => {
        const authData = new Uint8Array(newAssertion.response.authenticatorData);
        const clientDataJSON = new Uint8Array(newAssertion.response.clientDataJSON);
        const rawId = new Uint8Array(newAssertion.rawId);
        const sig = new Uint8Array(newAssertion.response.signature);
        const assertionClientExtensions = newAssertion.getClientExtensionResults();

        return {
            id: newAssertion.id,
            rawId: b64enc(rawId),
            type: newAssertion.type,
            authData: b64RawEnc(authData),
            clientData: b64RawEnc(clientDataJSON),
            signature: hexEncode(sig),
            assertionClientExtensions: JSON.stringify(assertionClientExtensions)
        };
    };

    /**
    * Post the assertion to the server for validation and logging the user in.
    * @param {Object} assertionDataForServer
    */
    const postAssertionToServer = async (assertionDataForServer) => {

        var form = document.createElement("form");
        form.method = "POST";
        form.action = "{% url "webauthin:login-verify" %}";
        form.style  = "display:none;"

        Object.entries(assertionDataForServer).forEach(([key, value]) => {
            var element = document.createElement("input");
            element.value=value;
            element.name=key;
            element.type="hidden";
            form.appendChild(element);
        });

        document.body.appendChild(form);

        form.submit();
    }


    document.addEventListener("DOMContentLoaded", e => {
        document.querySelector('#webauthin-login').addEventListener('click', didClickLogin);
    });
</script>
{% endblock %}

webauthin/templates/webauthin_register.html
<script>
    var lookup = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'

    ;(function (exports) {
        'use strict'

        var Arr = (typeof Uint8Array !== 'undefined')
        ? Uint8Array
        : Array

        var PLUS = '+'.charCodeAt(0)
        var SLASH = '/'.charCodeAt(0)
        var NUMBER = '0'.charCodeAt(0)
        var LOWER = 'a'.charCodeAt(0)
        var UPPER = 'A'.charCodeAt(0)
        var PLUS_URL_SAFE = '-'.charCodeAt(0)
        var SLASH_URL_SAFE = '_'.charCodeAt(0)

        function decode (elt) {
            var code = elt.charCodeAt(0)
            if (code === PLUS || code === PLUS_URL_SAFE) return 62 // '+'
            if (code === SLASH || code === SLASH_URL_SAFE) return 63 // '/'
            if (code < NUMBER) return -1 // no match
            if (code < NUMBER + 10) return code - NUMBER + 26 + 26
            if (code < UPPER + 26) return code - UPPER
            if (code < LOWER + 26) return code - LOWER + 26
        }

        function b64ToByteArray (b64) {
            var i, j, l, tmp, placeHolders, arr

            if (b64.length % 4 > 0) {
                throw new Error('Invalid string. Length must be a multiple of 4')
            }

            // the number of equal signs (place holders)
            // if there are two placeholders, than the two characters before it
            // represent one byte
            // if there is only one, then the three characters before it represent 2 bytes
            // this is just a cheap hack to not do indexOf twice
            var len = b64.length
            placeHolders = b64.charAt(len - 2) === '=' ? 2 : b64.charAt(len - 1) === '=' ? 1 : 0

            // base64 is 4/3 + up to two characters of the original data
            arr = new Arr(b64.length * 3 / 4 - placeHolders)

            // if there are placeholders, only get up to the last complete 4 chars
            l = placeHolders > 0 ? b64.length - 4 : b64.length

            var L = 0

            function push (v) {
                arr[L++] = v
            }

            for (i = 0, j = 0; i < l; i += 4, j += 3) {
                tmp = (decode(b64.charAt(i)) << 18) | (decode(b64.charAt(i + 1)) << 12) | (decode(b64.charAt(i + 2)) << 6) | decode(b64.charAt(i + 3))
                push((tmp & 0xFF0000) >> 16)
                push((tmp & 0xFF00) >> 8)
                push(tmp & 0xFF)
            }

            if (placeHolders === 2) {
                tmp = (decode(b64.charAt(i)) << 2) | (decode(b64.charAt(i + 1)) >> 4)
                push(tmp & 0xFF)
                } else if (placeHolders === 1) {
                tmp = (decode(b64.charAt(i)) << 10) | (decode(b64.charAt(i + 1)) << 4) | (decode(b64.charAt(i + 2)) >> 2)
                push((tmp >> 8) & 0xFF)
                push(tmp & 0xFF)
            }

            return arr
        }

        function uint8ToBase64 (uint8) {
            var i
            var extraBytes = uint8.length % 3 // if we have 1 byte left, pad 2 bytes
            var output = ''
            var temp, length

            function encode (num) {
                return lookup.charAt(num)
            }

            function tripletToBase64 (num) {
                return encode(num >> 18 & 0x3F) + encode(num >> 12 & 0x3F) + encode(num >> 6 & 0x3F) + encode(num & 0x3F)
            }

            // go through the array every three bytes, we'll deal with trailing stuff later
            for (i = 0, length = uint8.length - extraBytes; i < length; i += 3) {
                temp = (uint8[i] << 16) + (uint8[i + 1] << 8) + (uint8[i + 2])
                output += tripletToBase64(temp)
            }

            // pad the end with zeros, but make sure to not forget the extra bytes
            switch (extraBytes) {
                case 1:
                temp = uint8[uint8.length - 1]
                output += encode(temp >> 2)
                output += encode((temp << 4) & 0x3F)
                output += '=='
                break
                case 2:
                temp = (uint8[uint8.length - 2] << 8) + (uint8[uint8.length - 1])
                output += encode(temp >> 10)
                output += encode((temp >> 4) & 0x3F)
                output += encode((temp << 2) & 0x3F)
                output += '='
                break
                default:
                break
            }

            return output
        }

        exports.toByteArray = b64ToByteArray
        exports.fromByteArray = uint8ToBase64
    }(typeof exports === 'undefined' ? (this.base64js = {}) : exports))



    function b64enc(buf) {
        return base64js.fromByteArray(buf)
        .replace(/\+/g, "-")
        .replace(/\//g, "_")
        .replace(/=/g, "");
    }

    function b64RawEnc(buf) {
        return base64js.fromByteArray(buf)
        .replace(/\+/g, "-")
        .replace(/\//g, "_");
    }

    function hexEncode(buf) {
        return Array.from(buf)
        .map(function(x) {
            return ("0" + x.toString(16)).substr(-2);
        })
        .join("");
    }

    function urlsafe_b64decode(s) {
        return atob(s.replace(/\-/g, '+').replace(/_/g, '/'));
    }

    async function fetch_json(url, options) {
        const response = await fetch(url, options);
        const body = await response.json();
        if (body.fail)
        throw body.fail;
        return body;
    }

    /**
    * REGISTRATION FUNCTIONS
    */

    /**
    * Callback after the registration form is submitted.
    * @param {Event} e
    */
    const didClickRegister = async (e) => {
        e.preventDefault();

        if (navigator.credentials == undefined) {
            alert("Your browser doesn't support WebAuthn, please use a different browser.");
            return;
        }
        // gather the data in the form
        // post the data to the server to generate the PublicKeyCredentialCreateOptions
        let credentialCreateOptionsFromServer;
        try {
            credentialCreateOptionsFromServer = await getCredentialCreateOptionsFromServer();
        } catch (err) {
            alert("Failed to register key, please make sure your browser supports WebAuthn: " + credentialCreateOptionsFromServer)
            return console.error("Failed to register key, please make sure your browser supports WebAuthn: ", credentialCreateOptionsFromServer)
        }

        // convert certain members of the PublicKeyCredentialCreateOptions into
        // byte arrays as expected by the spec.
        const publicKeyCredentialCreateOptions = transformCredentialCreateOptions(credentialCreateOptionsFromServer);

        // request the authenticator(s) to create a new credential keypair.
        let credential;
        try {
            credential = await navigator.credentials.create({
                publicKey: publicKeyCredentialCreateOptions
            });
        } catch (err) {
            alert("Error creating credential:" + err);
            return console.error("Error creating credential:", err);
        }

        // we now have a new credential! We now need to encode the byte arrays
        // in the credential into strings, for posting to our server.
        const newAssertionForServer = transformNewAssertionForServer(credential);

        // post the transformed credential data to the server for validation
        // and storing the public key
        postNewAssertionToServer(newAssertionForServer);
    }

    /**
    * Get PublicKeyCredentialRequestOptions for this user from the server
    * formData of the registration form
    * @param {FormData} formData
    */
    const getCredentialCreateOptionsFromServer = async () => {
        return await fetch_json(
        "{% url "webauthin:register-begin" %}", {
            method: "POST",
        }
        );
    }

    /**
    * Transforms items in the credentialCreateOptions generated on the server
    * into byte arrays expected by the navigator.credentials.create() call
    * @param {Object} credentialCreateOptionsFromServer
    */
    const transformCredentialCreateOptions = (credentialCreateOptionsFromServer) => {
        let {challenge, user} = credentialCreateOptionsFromServer;
        user.id = Uint8Array.from(
        urlsafe_b64decode(credentialCreateOptionsFromServer.user.id), c => c.charCodeAt(0));

        challenge = Uint8Array.from(
        urlsafe_b64decode(credentialCreateOptionsFromServer.challenge), c => c.charCodeAt(0));

        const transformedCredentialCreateOptions = Object.assign(
        {}, credentialCreateOptionsFromServer,
        {challenge, user});

        return transformedCredentialCreateOptions;
    }



    /**
    * AUTHENTICATION FUNCTIONS
    */


    /**
    * Transforms the binary data in the credential into base64 strings
    * for posting to the server.
    * @param {PublicKeyCredential} newAssertion
    */
    const transformNewAssertionForServer = (newAssertion) => {
        const attObj = new Uint8Array(
        newAssertion.response.attestationObject);
        const clientDataJSON = new Uint8Array(
        newAssertion.response.clientDataJSON);
        const rawId = new Uint8Array(
        newAssertion.rawId);

        const registrationClientExtensions = newAssertion.getClientExtensionResults();

        return {
            id: newAssertion.id,
            rawId: b64enc(rawId),
            type: newAssertion.type,
            attObj: b64enc(attObj),
            clientData: b64enc(clientDataJSON),
            registrationClientExtensions: JSON.stringify(registrationClientExtensions)
        };
    }

    /**
    * Posts the new credential data to the server for validation and storage.
    * @param {Object} credentialDataForServer
    */
    const postNewAssertionToServer = async (credentialDataForServer) => {

        var form = document.createElement("form");
        form.method = "POST";
        form.action = "{% url "webauthin:register-verify" %}";   
        form.style  = "display:none;"

        Object.entries(credentialDataForServer).forEach(([key, value]) => {
            var element = document.createElement("input"); 
            element.value=value;
            element.name=key;
            element.type="hidden";
            form.appendChild(element);  
        });

        document.body.appendChild(form);
    
        form.submit();
    }

    document.addEventListener("DOMContentLoaded", e => {
        document.querySelector('#webauthin-register').addEventListener('click', didClickRegister);
    });
</script>